site_verificat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_verificat_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('profile/', user_views.profile, name='profile'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
              # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
# from django.urls import path
# from .views import profile
#
# urlpatterns = [
#     path('profile/', profile, name= 'users-profile'),
# ]

site_verificat_app/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Category(models.Model):
    name = models.CharField(max_length=50)
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class ServiceProvider(models.Model):
    PERSOANA_FIZICA = 'PF'
    COMPANIE = 'COM'
    TYPE_CHOICES = [
        (PERSOANA_FIZICA, 'Persoana_Fizica'),
        (COMPANIE, 'Companie')

    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default=PERSOANA_FIZICA, )
    phone_nr = models.CharField(max_length=20)
    email = models.EmailField(default="nimic@chiarnimic.wow")
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/product_images/', default='static/not_available.png')
    availability = models.BooleanField(default=True)
    latitude = models.FloatField(default=44.43282996363418)
    longitude = models.FloatField(default=26.097626053735162)

    # favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)

    # def __init__(self, *args, **kwargs):
    #     super().__init__(args, kwargs)
    #     self.fovourites = None

    def __str__(self):
        return f'{self.name}...'


class AboutUs(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=250)
    personal_info = models.TextField()
    email = models.EmailField(default="nimic@chiarnimic.wow")

    def __str__(self):
        return f'{self.name}'


class Beneficiary(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    phone_nr = models.CharField(max_length=20, blank=True)
    email = models.EmailField(default="nimic@chiarnimic.wow")
    application = models.TextField()
    image = models.ImageField(upload_to='static/product_images/', default='static/not_available.png')

    def __str__(self):
        return f'{self.name}'

# class BeneficiaryProfile(models.Model):
#     user = models.OneToOneField(Beneficiary, on_delete=models.CASCADE)
#     locality= models.CharField(max_length=20, blank=True)
#     judet=models.CharField(max_length=50, blank=True)


class Ad(models.Model):
    title = models.CharField(max_length=30)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    service_provider = models.ForeignKey(ServiceProvider, on_delete=models.CASCADE)
    type = models.CharField(max_length=50)
    image = models.ImageField(upload_to='static/product_images/', default='static/not_available.png')
    text_ad = models.TextField()
    additional_details = models.TextField()
    price = models.IntegerField()
    contact_person = models.CharField(max_length=30)
    phone_nr = models.CharField(max_length=20)
    email = models.EmailField(default="nimic@chiarnimic.wow")
    locality = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.title}'

    def get_rating(self):
        total = sum(int(review['stars']) for review in self.reviews.values())
        if self.reviews.count() == 0:
            return 0

        return total / self.reviews.count()


class BeneficiaryRequest(models.Model):
    title = models.CharField(max_length=30)
    beneficiary = models.ForeignKey(Beneficiary, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/product_images/', default='static/not_available.png')
    text = models.TextField()
    phone_nr = models.CharField(max_length=20)
    email = models.EmailField(default="nimic@chiarnimic.wow")
    locality = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.title}'


class Message(models.Model):
    title = models.CharField(max_length=20)
    image = models.ImageField(upload_to='static/product_images/', default='static/not_available.png')
    # user_name = models.CharField(max_length=20)
    message = models.TextField(max_length=100)
    date = models.DateField()
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_from')
    user_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_to')

    def __str__(self):
        return f'{self.title} {self.user_from} {self.user_to}'


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_provider = models.ForeignKey(ServiceProvider, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.ad}'


class ReviewRating(models.Model):
    service_provider = models.ForeignKey(ServiceProvider, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.CharField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class AdReviews(models.Model):
    ad = models.ForeignKey(Ad, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    stars = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.stars} {self.user} {self.ad}'



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    # service_providers = models.OneToOneField(ServiceProvider)
    # beneficiarys = models.OneToOneField(Beneficiary)
    # type = models.CharField(max_length=50)
    #
    image = models.ImageField(default='not_available_png', upload_to='profile_images')
    email = models.EmailField(default="nimic@chiarnimic.wow")
    phone = models.CharField(max_length=20)
    locality = models.CharField(max_length=50)

    # def __str__(self):
    #     return f'{self.user.username} Profile'  # show how we want it to be displayed
    # @receiver(post_save, sender=User)
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.profile.save()

    # ServiceProvider = models.ManyToManyField(ServiceProvider)

    # @receiver(post_save, sender=User)  # add this
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         UserProfile.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)  # add this
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.profile.save()

    # Override the save method of the model

    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.image.path)  # Open image
    #
    #     # resize image
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)  # Resize image
    #         img.save(self.image.path)  # Save it again and override the larger image

templates/pages/about_us.html
{% extends 'base2.html' %}
{% block body %}
    <style>
        .body_class {
            background-color: #ccaa11;
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
        }

        .html_class {
            box-sizing: border-box;
        }


        .column {
            float: left;
            width: 33.3%;
            margin-bottom: 16px;
            padding: 0 8px;
        }

        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            margin: 8px;
        }

        .about-section {
            padding: 50px;
            text-align: center;
            background-color: #474e5d;
            color: white;
        }

        .container {
            padding: 0 16px;
        }

        .container::after, .row::after {
            content: "";
            clear: both;
            display: table;
        }

        .title {
            color: grey;
        }

        .button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
        }

        .button:hover {
            background-color: #555;
        }

        @media screen and (max-width: 650px) {
            .column {
                width: 100%;
                display: block;
            }
        }

    </style>
    <div class="about-section">
        <h1>Despre noi</h1>
        <p>Obiectivul nostru este sa ii promovam pe cei care presteaza servicii de calitate in urma comentariilor postate de dumneavoastra</p>
        <p>Cand ai nevoie de un prestator de servicii, verificat deja de alte persoane, nu suna un prieten, cauta-l aici!</p>
    </div>

    <h2 style="text-align:center">Echipa noastra</h2>
    <div class="row" style="margin:auto;max-width:1000px;">
        <div class="column">
            <div class="card">
                <img src="https://images.unsplash.com/photo-1485875437342-9b39470b3d95?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2073&q=80" alt="Jane" style="width:100%">
                <div class="container">
                    <h2>Jane Doe</h2>
                    <p class="title">CEO & Founder</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>jane@example.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80" alt="Mike" style="width:100%">
                <div class="container">
                    <h2>Mike Ross</h2>
                    <p class="title">Art Director</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>mike@example.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="https://images.unsplash.com/photo-1592827095305-68f21edefb82?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80" alt="John" style="width:100%">
                <div class="container">
                    <h2>John Doe</h2>
                    <p class="title">Designer</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>john@example.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/ad_details.html
{% extends 'base2.html' %}
<style>
.notifications.space-below{
    margin-bottom: 20px;
}



</style>
{% block body %}
     <div class="container" style="margin-top: 200px">
        <div class="card">
            <div class="row g-0">
                <div class="col-md-6">
                    <div class="p-3 right-side">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 style="background-color:lightgrey;padding:2px;width:100%;"><b>{{ ad.title }} | {{ ad.type }}</b> </h5>
                            <span class="heart"><i class='bx bx-heart'></i></span>
                        </div>

                        <div class="mt-2 pr-3 content">
                            <p><b>Descriere anunt:</b></p>
                            <ul>
                                <li>{{ ad.text_ad }}</li>
                                <li>{{ ad.additional_details }}</li>
                            </ul>

                        </div>
                        <!--
                        <div class="d-flex justify-content-between align-items-center">
                             <span class="heart"><i class='bx bx-heart'></i></span>
                        </div>
                        -->
                         <div class="d-flex justify-content-between align-items-center">
                             <p><b>Persoana de contact:</b> {{ ad.contact_person }}</p>
                             <!-- <span class="heart"><i class='bx bx-heart'></i></span> -->
                        </div>
                        <div class="mt-2 pr-3 content">
                            <p><b>Tel:</b> {{ ad.phone_nr }}</p>
                        </div>
                        <div class="mt-2 pr-3 content">
                            <p> <b>Email:</b> {{ ad.email }}</p>
                        </div>
                         <div class="mt-2 pr-3 content">
                             <p> <b>Pret:</b> {{ ad.price }} LEI</p>
                             <p> <b>Stars:</b> {{ ad.get_rating|floatformat:1 }}</p>
                        </div>
                         <div class="mt-2 pr-3 content">
                            <p> <b>Localitate:</b> {{ ad.locality }}</p>
                        </div>

{#                        <h3>{{ service_provider.availability }}</h3>#}
                        <div class="ratings d-flex flex-row align-items-center">
                            <div class="d-flex flex-row"><i class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i
                                    class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i class='bx bx-star'></i>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col-md-6 border-end">
                    <div class="d-flex flex-column justify-content-center">
                        <div class="main_image">
                            <img style="width:100%;height:auto;object-fit: cover;" src="https://images.unsplash.com/photo-1593786267440-550458cc882a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1074&q=80" id="main_product_image"></div>
                    </div>
                </div>
                <hr>
                <h5 style="background-color:lightgrey;padding:2px;width:100%;">Reviews</h5>
                <div class="reviews-wrapper" style="font-size:12px;">
                    {% for review in ad.reviews.all %}
                        <div class="notification space-below">
                            <p>
                                <strong>Date:</strong>{{ review.date_added|date:"Y-m-d" }}
                                <br>
                                <strong>Stars:</strong>{{ review.stars }}
                            </p>
                            {{ review.content }}
                        </div>
                        {% empty %}
                        <div class="notifications space-below" style="font-size:12px;">
                            No reviews yet...
                        </div>
                    {% endfor %}
                </div>
                <div class="notifications space-below" style="font-size:12px;">
                    {% if request.user.is_authenticated and perms.site_verificat_app.add_beneficiaryrequest %}



                        <form method="post" action="" style="top:50px;max-width:100%;">
                            {% csrf_token %}


                            <div style="display:flex;">

                                <div class="field" style="width:15%;">
                                    <label>Stars</label>
                                    <div class="control">
                                        <div class="select">
                                            <select name="stars" style="width:100%;height:50px;">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3" selected>3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>

                                            </select>

                                        </div>

                                    </div>

                                </div>

                                <div class="field" style="width:70%;">
                                    <label>Content</label>

                                    <div class="control">
                                        <textarea class="textarea" name="content" style="width:100%;height:50px;"></textarea>
                                    </div>
                                </div>

                                <div class="field" style="width:15%;">
                                <div class="control">
                                    <label></label>
                                    <button class="button is-success" style="width:100%;height:50px;">Submit</button>
                                </div>
                            </div>

                            </div>

                        </form>
                    {% else %}
                        <p>Please sign in to add reviews!</p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/addcomment.html
{% extends 'pages/admin_page.html' %}
{% extends 'base2.html' %}

{% block title %} Add Comment {% endblock %}
{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Comment</button>
    </form>

{% endblock %}

templates/pages/beneficiary_all_view.html
{% extends 'pages/admin_page.html' %}

{% block title %} All Beneficiaries View {% endblock %}
{% block admin_content %} {# de modificat #}
{#    <a class="btn btn-success"#}
{#       href="{% url 'category_create' %}" style="margin-top: 120px;">Create</a>#}
    <div class="row">
        {% for beneficiary in beneficiaries %}
            <div class="card col-xl-3 col-lg-4 col-md-6 col-sm-12 border-primary border-2 mb-1 me-1"
                 style="max-width: 20rem;">
                <div class="card-header fw-bold">{{ beneficiary.name }}</div>
                <div class="card-body">
                    {% if perms.site_verificat_app.change_beneficiary %}
                        <a class="btn btn-primary btn-sm" href="{% url 'beneficiary_update' beneficiary.id %}" role="button">Update</a>
                    {% endif %}

                    {% if perms.site_verificat_app.change_beneficiary %}
                        <a class="btn btn-danger btn-sm" href="{% url 'beneficiary_delete' beneficiary.id %}" role="button">Delete</a>
                    {% endif %}

                    <a class="btn btn-secondary btn-sm" href="{% url 'beneficiary_details' beneficiary.id %}" role="button">Beneficiary
                        details</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/pages/beneficiary_delete.html
{% extends 'pages/admin_page.html' %}

{% block title %} Delete Beneficiary {% endblock %}
{% block admin_content %}
    <p>Are you sure you want to delete {{ beneficiary.name }}</p>
    <form method="post">
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        <button type="submit">Delete Beneficiary</button>
    </form>

{% endblock %}

templates/pages/beneficiary_update.html
{% extends 'pages/admin_page.html' %}

{% block title %} Update Beneficiary {% endblock %}
{% block admin_content %}
    <form method="post" enctype="multipart/form-data">
{#   enctype="multipart/form-data" - ne trebuie ca sa mearga upload-ul de fisiere (in cazul de fata imaginea de articol) #}
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        {{ form.as_p }}
        <button type="submit">Update Beneficiary</button>
    </form>

{% endblock %}

templates/pages/category_details.html
{% extends 'base2.html' %}
{#<style>#}
{#    .detailsCards {#}
{#        max-width:800px;#}
{#        margin:auto;#}
{#        text-align:center;#}
{#    }#}
{##}
{#    .titleCard {#}
{#        margin-bottom:60px;#}
{#        margin-top:60px;#}
{#    }#}
{##}
{##}
{#    .card {#}
{#        display: flex;#}
{#        flex-direction: row;#}
{#        padding:0px;#}
{#        height:170px;#}
{#        margin-bottom:10px;#}
{#    }#}
{##}
{#    .imgCard {#}
{#        width:30%;#}
{#        border:4px solid white;#}
{##}
{#    }#}
{##}
{#    .card-img-top {#}
{#        width:100%;#}
{#        height:100%;#}
{#        object-fit: cover;#}
{#    }#}
{##}
{#    .card-body {#}
{#        width:70%;#}
{#        position:relative;#}
{#    }#}
{##}
{#    .round {#}
{#        position:absolute;#}
{#        background-color:red;#}
{#        color:white;#}
{#        font-size:14px;#}
{#        width:100px;#}
{#        height:100px;#}
{#        border-radius: 100px;#}
{#        top:0px;#}
{#        left:0px;#}
{#        padding:40px 0px;#}
{#    }#}
{##}
{#</style>#}
{% block body %}
{#    {% include 'partials/title_and_products_block.html' with title=category.name %}#}
{#    {% include 'partials/title_and_categories_block.html' with title=category.name %}#}
    {% include 'partials/title_and_ads_block.html' with title=category.name %}
{#    {% include 'partials/title_and_beneficiary_block.html' with title=category.name %}#}
{#    {% include 'partials/title_and_beneficiary_request_block.html' with title=category.name %}#}
{#    {% include 'partials/title_and_message_block.html' with title=category.name %}#}

{#    <div class="container-xl detailsCards">#}
{#        <h3 class="titleCard">{{ title }}</h3>#}
{#        <div class="titleCards row">#}
{#            {% for ad in ads %}#}
{#                <!-- col-xl-3 col-lg-4 col-md-6 col-sm-12 ASTEA TINEAU DE CARD -->#}
{#                <div class="card">#}
{#                    <div class="imgCard">#}
{#                        <img src="{{ ad.image.url }}" class="card-img-top" alt="{{ ad.title }}">#}
{#                    </div>#}
{##}
{#                    <div class="card-body">#}
{#                        <!-- <div class="round">{{ ad.type }}</div> -->#}
{#                       <h4 class="card-title"><strong>{{ ad.title }}</strong> | {{ ad.type }}</h4>#}
{#                    <p class="card-text">{{ ad.email }}<br>{{ ad.text_ad }} <strong>Tel:</strong> {{ ad.phone_nr }}</p>#}
{#                    <a href="#" class="btn btn-primary m-1">Adauga in lista</a>#}
{#                    <a href="{% url 'ad_details' ad.id %}" class="btn btn-secondary m-1">Detalii suplimentare</a>#}
{#                        </p>#}
                        {#                        <a href="#" class="btn btn-primary m-1">Adauga in lista favorite</a>#}
                        {#    pentru a trimite mesaj preastorului <a href="{% url 'service_provider_details' service_provider.id %}" class="btn btn-secondary m-1">Detalii suplimentare</a>#}
{##}
{#                    </div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}

{% endblock %}

templates/pages/message_all_view.html
{% extends 'pages/admin_page.html' %}
{% block title %} All Message View {% endblock %}
{% block admin_content %}
{#    <a class="btn btn-success"#}
{#       href="{% url 'category_create' %}" style="margin-top: 120px;">Create</a>#}
    <div class="row">
        {% for message in messages %}
            <div class="card col-xl-3 col-lg-4 col-md-6 col-sm-12 border-primary border-2 mb-1 me-1"
                 style="max-width: 20rem;">
                <div class="card-header fw-bold">{{ message.title }}</div>
                <div class="card-body">
{#                    {% if perms.site_verificat_app.change_message %}#}
{#                        <a class="btn btn-primary btn-sm" href="{% url 'message_update' ad.id %}" role="button">Update</a>#}
{#                    {% endif %}#}

                    {% if perms.site_verificat_app.change_message %}
                        <a class="btn btn-danger btn-sm" href="{% url 'message_delete' message.id %}" role="button">Delete</a>
                    {% endif %}

                    <a class="btn btn-secondary btn-sm" href="{% url 'message_details' message.id %}" role="button">Message
                        details</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/pages/profile.html
{% extends 'base2.html' %}
{% block title %}Profil{% endblock title %}
{% block content %}
<h1>
Test
</h1>
    <section class="section-content padding-y bg">

        <div class="container">
            <div class="row">
                <main class="col-md-9">
                    <article class="card">
                        <header class="card-header">
                            <strong class="d-inline-block mr-3"> Edit your profile</strong>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form action="{% url 'profile' %}" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label>Name</label>
                                                {{ user_form.name }}
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label>E-mail</label>
                                                {{ user_form.email }}
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label>Phone Number</label>
                                                {{ user_form.phone_nr }}
                                            </div>
                                        </div>
{#                                        <div class="form-group">#}
{#                                            <label>Locality</label>#}
{#                                            {{ profile_form.locality }}#}
{#                                        </div>#}
{#                                        <div class="form-group">#}
{#                                            <label>Judet</label>#}
{#                                            {{ profile_form.judet}}#}
{#                                        </div>#}
                                        <input type="submit" value="Save" class="btn btn-primary">
                                    </form>
                                </div>

                            </div> <!-- row.// -->
                        </div> <!-- card-body .// -->
                    </article> <!-- order-group.// -->
                </main>
            </div> <!-- row.// -->
        </div>


    </section>

{% endblock %}



{#{% block head %}#}
{#    <title>Profile</title>#}
{#{% endblock %}#}
{#{% block body %}#}
{#    <div class="container">#}
{#    <h1>Profile</h1>#}
{#    <p>Username: {{ user }}</p>#}
{#    <p>Name: {{ user.name }}</p>#}
{#    <p>Email: {{ user.email }}</p>#}
{#    <p>Phone: {{ user.profile.phone }}</p>#}
{#    <p>Description: {{ user.profile.description }}</p>#}
{#    </div>#}
{#{% endblock %}#}

templates/pages/rating_all_view.html
{#{% extends 'pages/admin_page.html' %}#}
{##}
{#{% block title %} All Ratings View {% endblock %}#}
{#{% block body %}#}
{#    <a class="btn btn-success"#}
{#       href="{% url 'category_create' %}" style="margin-top: 120px;">Create</a>#}
{#    <div class="row">#}
{#        {% for rating in ratings %}#}
{#            <div class="card col-xl-3 col-lg-4 col-md-6 col-sm-12 border-primary border-2 mb-1 me-1"#}
{#                 style="max-width: 20rem;">#}
{#                <div class="card-header fw-bold">{{ rating.rate }}</div>#}
{#                <div class="card-body">#}
{#                    {% if perms.site_verificat_app.change_rating %}#}
{#                        <a class="btn btn-danger btn-sm" href="{% url 'rating_delete' rating.id %}" role="button">Delete</a>#}
{#                    {% endif %}#}
{##}
{#                    <a class="btn btn-secondary btn-sm" href="{% url 'rating_details' rating.id %}" role="button">Rating#}
{#                        details</a>#}
{#                </div>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
{#{% endblock %}#}

templates/pages/rating_create.html
{#{% extends 'base.html' %}#}
{#{% extends 'pages/admin_page.html' %}#}
{##}
{#{% block title %} Adauga Rating {% endblock %}#}
{#{% block body %}#}
{#    <form method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Adauga Rating</button>#}
{#    </form>#}
{##}
{#{% endblock %}#}